name: Chair11
favicon: null
layout_spectrum: 0.89368
typography_spectrum: 0.07188
title: Chair 11
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#11120c'
    - '#c6c9b8'
    - '#a3ac8f'
    - '#7f8498'
    - '#7b5212'
  brandStrength: 0.6578511062543839
  lightness: 0.75
  saturation: 0.6380112341139466
  rhythmicContrast: 0.75
purpose: []
